[package]
name = "search_in_files"
version = "0.1.0"
edition = "2021"

[dependencies]
app_properties = "0.1.2"
grep-searcher = "0.1.14"
grep-matcher = "0.1.7"
grep-regex = "0.1.13"
regex = "1.11.1"
walkdir = "2.5.0"